spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sport?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: sport
    password: a88915388


mybatis:
  mapper-locations: classpath:mapper/*.xml


server:
  port: 8888

logging:
  level:
    com:
      hezong:
        dao: debug

imageDirectory: D:/IDEAProj/sprot/front end/sport/src/assets/image/

